name: Economy
main: com.brysonm.uconomy.uConomy
version: 1.0
authors: [brysonm, stuntguy3000]
commands:
    sell:
        description: ""
    balance:
        description: "See how much money you have.""
    deposit:
        description: ""
    withdraw:
        description: ""
    buy:
        description: ""
    price:
        description: ""